[env]
PULUMI_ROOT = "{{config_root}}/.root"

_.path = [
  "{{env.PULUMI_ROOT}}/bin",
]

[tools]
changie = "latest"
go = "1.24"
gofumpt = "0.9.1"
golangci-lint = "2.5.0"
gotestsum = "latest"
pulumi = "latest"
"vfox:dotnet" = "8.0"
